wifi_ssid: "dummy_wifi_ssid"
wifi_password: "dummy_wifi_password"
wifi_domain: ".dummy_wifi_domain"

ota_password: "dummy_ota_password"

mqtt_broker: "dummy_mqtt_broker"

home_timezone: "Etc/UTC" # has to be a a valid timezone
home_latitude: 00.0000000
home_longitude: 0.0000000

