esphome:
  name: 433mhzreceiver
  platform: ESP8266
# board: d1
  board: d1_mini

#  libraries:
#    - https://github.com/dl9sec/ArduinoSIP.git#c4baefe
  includes:
    - "ArduinoSIP/SipSwitch.h"

<<: !include common/substitutions.yaml
packages: 
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  management: !include common/management.yaml
  
logger: 

sensor:
  - platform: wifi_signal
    name: "wifi-signal-strength"
    update_interval: 60s

switch:
- platform: custom
  lambda: |-
    auto sipswitch = new SipSwitch();
    App.register_component(sipswitch);
    return {sipswitch};
  switches:
    id: sip
    name: "My Custom Switches"

remote_receiver:
  pin:
    # number: D0 # GPIO16
    number: D1
    inverted: true
    mode:
      input: true
      pullup: true
    
  # https://community.home-assistant.io/t/turning-433mhz-doorbell-into-a-smart-doorbell/373214/2
  dump:  rc_switch
  tolerance: 60%
  # tolerance: 25%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb  
  

binary_sensor:
  - platform: remote_receiver
    name: "one"
    rc_switch_raw: 
      protocol: 2
      code: "01011010010100011110"
    on_press:
      then: 
        - logger.log: "Ding dong"
        - switch.turn_off: sip
    filters:
      delayed_off: 5s

