# showcase: ESP via HW reset aufwachen lassen (leak detected)

esphome:
  name: leakdetector
  platform: ESP8266
  board: esp12e

<<: !include common/substitutions.yaml
packages: 
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  management: !include common/management.yaml

logger:

# note that on the ESP8266 GPIO16 (D0) must be connected to the RST pin so that it will wake up again. 
deep_sleep:
  run_duration: 20s
  sleep_duration: 1min
  # sleep_duration: 6h

sensor:
  - platform: wifi_signal
    name: "wifi-signal-strength"
    update_interval: 60s
  - platform: adc
    pin: VCC
    name: "VCC Voltage"

binary_sensor:
  - platform: gpio
    id: washingmachine_leak
    pin:
      number: GPIO2 # (D4)
      inverted: True
