esphome:
  name: lebendfalle
  platform: ESP8266
  board: d1_mini
  # board: esp01
  on_boot:
    then:
      - script.execute: script_heartbeat

<<: !include common/substitutions.yaml
packages: 
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  management: !include common/management.yaml

globals:
   - id: catched
     type: long

sensor:
  - platform: wifi_signal
    name: "wifi-signal-strength"
    update_interval: 5min

binary_sensor:
  - platform: gpio
    pin:
      number: D5
      inverted: true
      mode:
        input: true
        pullup: true
    id: tuere
    name: 'tuere'
    filters:
      - delayed_on: 100ms
      - delayed_off: 100ms
    on_press:
      - script.stop: script_heartbeat
      - script.execute: script_catched
      - globals.set:
          id: catched
          value: !lambda return millis();
    on_release:
      - script.stop: script_catched
      - script.execute: script_heartbeat
      - globals.set:
          id: catched
          value: "0"
      
switch:
  - platform: gpio
    pin: D4
    inverted: true
    id: status_indicator
    internal: true

interval:
  - interval: 10min
    then:
      lambda: id(tuere).publish_state(id(tuere).state);

script:
  - id: script_heartbeat
    mode: queued
    then:
      - switch.turn_on: status_indicator
      - delay: 3s
      - switch.turn_off: status_indicator
      - delay: 500ms
      - script.execute: script_heartbeat
  - id: script_catched
    mode: queued
    then:
      - switch.turn_on: status_indicator
      - delay: 50ms
      - switch.turn_off: status_indicator
      - delay: 50ms
      - script.execute: script_catched
