substitutions:
  device_name: "pushbutton1"

esphome:
  name: ${device_name}

esp8266:
  board: d1_mini

<<: !include common/substitutions.yaml
packages: 
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  management: !include common/management.yaml

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 1min
    id: wifi_signal_db
  - platform: copy
    source_id: wifi_signal_db
    id: wifi_signal_percent
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "Signal %"

binary_sensor:
  - platform: gpio
    pin:
      number: D2
      mode: INPUT_PULLUP
      inverted: True
    id: push_button
    name: "Push Button"

    on_multi_click:
      - timing:
          - ON for at most 1.5s
          - OFF for at least 0.25s
        then:
          - mqtt.publish:
              topic: "${device_name}/single_click"
              payload: "ON"

      - timing:
          - ON for at most 1s
          - OFF for at most 0.50s
          - ON for at most 1s
          - OFF for at least 0.50s
        then:
          - mqtt.publish:
              topic: "${device_name}/double_click"
              payload: "ON"

      - timing:
          - ON for at least 1.5s
        then:
          - mqtt.publish:
              topic: "${device_name}/long_press"
              payload: "ON"

