substitutions:
  device_name: "scanservjs-controller"

esphome:
  name: ${device_name}

esp8266:
  board: d1_mini

<<: !include common/substitutions.yaml
packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  management: !include common/management.yaml

i2c:

font:
  - file: "fonts/Arial.ttf"
    id: arial12
    size: 12

globals:
  - id: scan_server
    type: std::string
    initial_value: '"http://scanservjs"'

  - id: ui_state        # 0: menu, 1: edit, 2: scanning, 3: flatbed multi, 4: done
    type: int
    initial_value: '0'

  - id: button_up_state
    type: bool
    initial_value: 'false'

  - id: button_down_state
    type: bool
    initial_value: 'false'

  - id: select_locked
    type: bool
    initial_value: 'false'

  - id: dpi
    type: int
    initial_value: '300'

  - id: color_mode      # 0: Lineart, 1: Gray, 2: Color
    type: int
    initial_value: '1'

  - id: source          # 0: Flatbed, 1: ADF
    type: int
    initial_value: '0'

  - id: flatbed_mode    # 0: Single, 1: Multi
    type: int
    initial_value: '0'

  - id: adf_mode        # 0: Simplex, 1: Duplex
    type: int
    initial_value: '0'

http_request:
  id: http_client
  useragent: ${device_name}
  verify_ssl: False
  timeout: 2min

display:
  - platform: ssd1306_i2c
    id: oled
    model: "SSD1306 64x48"
    address: 0x3C
    pages:

      # ---- DPI PAGE ----
      - id: page_dpi
        lambda: |-
          it.print(0,0,id(arial12),"DPI:");
          it.printf(0,12,id(arial12),"%d", id(dpi));

      # ---- COLOR MODE PAGE ----
      - id: page_color
        lambda: |-
          const char* colors[] = {"Lineart","Gray","Color"};
          it.print(0,0,id(arial12),"Color mode:");
          it.printf(0,12,id(arial12),"%s", colors[id(color_mode)]);

      # ---- SOURCE PAGE ----
      - id: page_source
        lambda: |-
          const char* sources[] = {"Flatbed","ADF"};
          it.print(0,0,id(arial12),"Source:");
          it.printf(0,12,id(arial12),"%s", sources[id(source)]);

      # ---- FLATBED/ADF PAGE ----
      - id: page_mode
        lambda: |-
          if(id(source)==0){
            const char* flatbed[] = {"Single","Multi"};
            it.print(0,0,id(arial12),"Flatbed mode:");
            it.printf(0,12,id(arial12),"%s", flatbed[id(flatbed_mode)]);
          } else {
            const char* adf[] = {"Simplex","Duplex"};
            it.print(0,0,id(arial12),"ADF mode:");
            it.printf(0,12,id(arial12),"%s", adf[id(adf_mode)]);
          }

      # ---- START SCAN PAGE ----
      - id: page_start
        lambda: |-
          it.print(0,0,id(arial12),"START SCAN");

      # ---- SCANNING PAGE ----
      - id: scanning_page
        lambda: |-
          it.print(0,24,id(arial12),"Scanning...");

      # ---- FLATBED MULTI ----
      - id: flatbed_multi
        lambda: |-
          const char* actions[] = {"SAME","NEXT","FIN"};
          int y=0;
          for(int i=0;i<3;i++){
            it.printf(0,y,id(arial12),"%s", actions[i]);
            y+=12;
          }

      # ---- SCAN DONE ----
      - id: scan_done
        lambda: |-
          it.print(0,24,id(arial12),"Scan done");

# ---- SCRIPT TO START SCAN ----
script:
  - id: start_scan
    then:
      - lambda: |-
          id(ui_state)=2;
          id(oled).show_page(id(scanning_page));

      - http_request.post:
          url: !lambda |-
            return id(scan_server) + "/api/v1/scan";
          request_headers:
            Content-Type: application/json
          body: !lambda |-
            std::string colors[] = {"Lineart","Gray","Color"};
            std::string sources[] = {"Flatbed","ADF"};
            std::string adf_s[] = {"Simplex","Duplex"};
            std::string flatbed_s[] = {"Single","Multi"};

            std::string json =
              std::string("{\"params\":{") +
              "\"resolution\":" + to_string(id(dpi)) + "," +
              "\"mode\":\"" + colors[id(color_mode)] + "\"," +
              "\"source\":\"" + sources[id(source)] + "\"," +
              "\"adfMode\":\"" + adf_s[id(adf_mode)] + "\"" +
              "},\"pipeline\":\"JPG | @:pipeline.high-quality\"}";

            return json;

          on_response:
            then:
              - lambda: |-
                  if(id(source)==0 && id(flatbed_mode)==1){
                    id(ui_state)=3;
                    id(oled).show_page(id(flatbed_multi));
                  } else {
                    id(ui_state)=4;
                    id(oled).show_page(id(scan_done));
                  }

          on_error:
            then:
              - lambda: |-
                  ESP_LOGE("scan","Scan failed");

# ---- SELECT BUTTON SCRIPT ----
  - id: button_select_sim
    then:
      - lambda: |-
          if(id(select_locked)) return;
          id(select_locked)=true;

          if(id(ui_state)==0 || id(ui_state)==1){
            // Press select to edit or start scan
            id(ui_state)=1;
          } else if(id(ui_state)==3){ // flatbed multi
            id(start_scan).execute();
          } else if(id(ui_state)==4){
            id(ui_state)=0;
            id(oled).show_page(id(page_dpi));
          }

# ---- BUTTONS ----
binary_sensor:
  - platform: gpio
    pin: D3  # UP button
    name: "Button Up"
    on_press:
      # If both buttons pressed → simulate SELECT
      - lambda: |-
          if (id(button_down_state) && !id(select_locked)) {
            id(button_select_sim).execute();
          }
      # Otherwise → go to previous page
      - display.page.show_previous: oled
      - component.update: oled
    on_release:
      - lambda: |-
          id(button_up_state) = false;
          id(select_locked) = false;

  - platform: gpio
    pin: D4  # DOWN button
    name: "Button Down"
    on_press:
      # If both buttons pressed → simulate SELECT
      - lambda: |-
          if (id(button_up_state) && !id(select_locked)) {
            id(button_select_sim).execute();
          }
      # Otherwise → go to next page
      - display.page.show_next: oled
      - component.update: oled
    on_release:
      - lambda: |-
          id(button_down_state) = false;
          id(select_locked) = false;

  - platform: gpio
    pin: D5  # SELECT button
    name: "Button Select"
    on_press:
      - script.execute: button_select_sim
