substitutions:
  device_name: "scanservjs-controller"

esphome:
  name: ${device_name}

esp8266:
  board: d1_mini

<<: !include common/substitutions.yaml
packages: 
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  management: !include common/management.yaml

i2c:

font:
  - file: "fonts/Arial.ttf"
    id: arial12
    size: 12

globals:
  - id: ui_state        # 0 menu,1 edit,2 scanning,3 multi,4 done
    type: int
    initial_value: '0'

  - id: cursor
    type: int
    initial_value: '0'

  - id: menu_last_index
    type: int
    initial_value: '4'

  - id: blink
    type: bool
    initial_value: 'false'

  - id: dpi
    type: int
    initial_value: '300'

  - id: color_mode      # 0 lineart,1 gray,2 color
    type: int
    initial_value: '2'

  - id: source          # 0 flatbed,1 adf
    type: int
    initial_value: '0'

  - id: flatbed_mode    # 0 single,1 multi
    type: int
    initial_value: '0'

  - id: adf_mode        # 0 simplex,1 duplex
    type: int
    initial_value: '0'

  - id: scan_server
    type: std::string
    initial_value: '"http://scanservjs"'


interval:
  - interval: 400ms
    then:
      - lambda: |-
          if (id(ui_state) == 1)
            id(blink) = !id(blink);
          else
            id(blink) = false;


http_request:
  id: http_client
  useragent: ${device_name}
  verify_ssl: False
  timeout: 15s


display:
  - platform: ssd1306_i2c
    id: oled
    model: "SSD1306 64x48"
    address: 0x3C
    pages:

      - id: main_menu
        lambda: |-
          const char* color[] = {"Lineart","Gray","Color"};
          const char* source_s[] = {"Flatbed","ADF"};
          const char* flatbed[] = {"Single","Multi"};
          const char* adf[] = {"Simplex","Duplex"};

          int y = 0;
          int row_index = 0;

          auto row = [&](int idx, const char* label, std::string value) {
            bool selected = (id(cursor) == idx);
            bool editing = (id(ui_state) == 1 && selected);

            if (selected) {
              if (editing && id(blink))
                it.printf(0, y, id(arial12), "  %s: %s", label, value.c_str());
              else
                it.printf(0, y, id(arial12), "> %s: %s", label, value.c_str());
            } else {
              it.printf(0, y, id(arial12), "  %s: %s", label, value.c_str());
            }

            y += 12;
          };

          row(row_index++, "DPI", to_string(id(dpi)));
          row(row_index++, "Color", color[id(color_mode)]);
          row(row_index++, "Source", source_s[id(source)]);

          if (id(source) == 0)
            row(row_index++, "Flatbed", flatbed[id(flatbed_mode)]);
          else
            row(row_index++, "ADF", adf[id(adf_mode)]);

          if (id(cursor) == row_index)
            it.print(0, y, id(arial12), "> START SCAN");
          else
            it.print(0, y, id(arial12), "  START SCAN");

          id(menu_last_index) = row_index;


      - id: scanning_page
        lambda: |-
          it.print(0, 24, id(arial12), "Scanning...");

      - id: flatbed_multi
        lambda: |-
          it.print(0, 0, id(arial12), "Next action:");
          it.print(0, 16, id(arial12), "Up: Same page");
          it.print(0, 32, id(arial12), "Down: Next page");
          it.print(0, 48, id(arial12), "Select: Finish");

      - id: scan_done
        lambda: |-
          it.print(0, 24, id(arial12), "Scan finished");


script:
  - id: start_scan
    then:
      - lambda: |-
          id(ui_state) = 2;
          id(oled).show_page(id(scanning_page));

      - http_request.post:
          url: !lambda |-
            return id(scan_server) + "/api/v1/scan";
          request_headers:
            Content-Type: application/json
          body: !lambda |-
            std::string mode[] = {"Lineart","Gray","Color"};
            std::string source_s[] = {"Flatbed","ADF"};
            std::string adf_s[] = {"Simplex","Duplex"};

            std::string json =
              std::string("{\"params\":{") +
              "\"resolution\":" + to_string(id(dpi)) + "," +
              "\"mode\":\"" + mode[id(color_mode)] + "\"," +
              "\"source\":\"" + source_s[id(source)] + "\"," +
              "\"adfMode\":\"" + adf_s[id(adf_mode)] + "\"" +
              "},\"pipeline\":\"JPG | @:pipeline.high-quality\"}";

            return json;

          on_response:
            then:
              - lambda: |-
                  if (id(source)==0 && id(flatbed_mode)==1) {
                    id(ui_state) = 3;
                    id(oled).show_page(id(flatbed_multi));
                  } else {
                    id(ui_state) = 4;
                    id(oled).show_page(id(scan_done));
                  }

          on_error:
            then:
              - lambda: |-
                  ESP_LOGE("scan", "Scan failed");


binary_sensor:
  - platform: gpio
    pin: D5
    name: D5
    on_press:
      then:
        - lambda: |-
            if (id(ui_state) == 0) {
              id(cursor) = (id(cursor) + id(menu_last_index)) % (id(menu_last_index)+1);
            } else if (id(ui_state) == 1) {
              switch(id(cursor)) {
                case 0: id(dpi)+=25; break;
                case 1: id(color_mode)=(id(color_mode)+1)%3; break;
                case 2: id(source)=(id(source)+1)%2; break;
                case 3:
                  if (id(source)==0) id(flatbed_mode)=(id(flatbed_mode)+1)%2;
                  else id(adf_mode)=(id(adf_mode)+1)%2;
                  break;
              }
            } else if (id(ui_state) == 3) {
              id(start_scan).execute();
            }

  - platform: gpio
    pin: D3
    name: button_up
    on_press:
      then:
        - lambda: |-
            if (id(ui_state) == 0) {
              id(cursor) = (id(cursor) + 1) % (id(menu_last_index)+1);
            } else if (id(ui_state) == 1) {
              switch(id(cursor)) {
                case 0: id(dpi)-=25; break;
                case 1: id(color_mode)=(id(color_mode)+2)%3; break;
                case 2: id(source)=(id(source)+1)%2; break;
                case 3:
                  if (id(source)==0) id(flatbed_mode)=(id(flatbed_mode)+1)%2;
                  else id(adf_mode)=(id(adf_mode)+1)%2;
                  break;
              }
            } else if (id(ui_state) == 3) {
              id(start_scan).execute();
            }

  - platform: gpio
    pin: D4
    name: button_down
    on_press:
      then:
        - lambda: |-
            if (id(ui_state) == 0) {
              if (id(cursor) == id(menu_last_index)) {
                id(start_scan).execute();
              } else {
                id(ui_state) = 1;
              }
            } else if (id(ui_state) == 1) {
              id(ui_state) = 0;
            } else if (id(ui_state) == 3) {
              id(ui_state) = 4;
              id(oled).show_page(id(scan_done));
            } else if (id(ui_state) == 4) {
              id(ui_state) = 0;
              id(oled).show_page(id(main_menu));
            }
