substitutions:
  device_name: "scanservjs-controller"

esphome:
  name: ${device_name}

esp8266:
  board: d1_mini

<<: !include common/substitutions.yaml
packages:
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  management: !include common/management.yaml

i2c:

font:
  - file: "fonts/Arial.ttf"
    id: arial12
    size: 12

# ---------------- GLOBAL STATE ----------------
globals:
  - id: scan_server
    type: std::string
    initial_value: '"http://scanservjs"'

  - id: status_str
    type: std::string
    initial_value: '""'

http_request:
  id: http_client
  useragent: ${device_name}
  verify_ssl: false
  timeout: 2min

# ---------------- DISPLAY ----------------
display:
  - platform: ssd1306_i2c
    id: oled
    model: "SSD1306 64x48"
    address: 0x3C

# ---------------- SELECTS ----------------
select:
  - platform: template
    id: dpi_select
    optimistic: true
    options: ["600","1200","75","100","150","200","300"]

  - platform: template
    id: color_select
    optimistic: true
    options: ["Gray","Color","Lineart"]

  - platform: template
    id: source_select
    optimistic: true
    options: ["Flatbed","ADF"]

  - platform: template
    id: flatbed_mode_select
    optimistic: true
    options: ["Single","Multi"]

  - platform: template
    id: adf_mode_select
    optimistic: true
    options: ["Simplex","Duplex"]

# ---------------- MENU ----------------
graphical_display_menu:
  id: scanner_menu
  display: oled
  font: arial12
  mode: rotary

  items:
    # DPI
    - type: select
      text: "DPI"
      select: dpi_select

    # Color
    - type: select
      text: "Col"
      select: color_select

    # Source
    - type: select
      text: "Src"
      select: source_select

    # Flatbed mode (only meaningful if Flatbed)
    - type: select
      text: "Mode"
      select: flatbed_mode_select

    # ADF mode (only meaningful if ADF)
    - type: select
      text: "ADF"
      select: adf_mode_select

    # Start scan command
    - type: command
      text: "Start Scan"
      on_value:
        then:
          - lambda: 'id(status_str) = "Scanning...";'
          - http_request.post:
              url: !lambda 'return id(scan_server) + "/api/v1/scan";'
              request_headers:
                Content-Type: application/json
              body: !lambda |-
                std::string dpi = id(dpi_select).current_option();
                std::string color = id(color_select).current_option();
                std::string source = id(source_select).current_option();

                std::string mode =
                  (source == "Flatbed")
                    ? id(flatbed_mode_select).current_option()
                    : id(adf_mode_select).current_option();

                return
                  "{\"params\":{"
                    "\"resolution\":" + dpi + ","
                    "\"mode\":\"" + color + "\","
                    "\"source\":\"" + source + "\","
                    "\"adfMode\":\"" + mode + "\""
                  "},\"pipeline\":\"JPG | @:pipeline.high-quality\"}";
              on_response:
                then:
                  - lambda: 'id(status_str) = "Scan done";'

              on_error:
                then:
                  - lambda: 'id(status_str) = "Scan failed";'

    - type: label
      text: !lambda 'return id(status_str);'

# ---------------- BUTTONS ----------------
binary_sensor:
  - platform: gpio
    pin:
      number: D3
      mode: INPUT_PULLUP
      inverted: True
    name: "Button Up"
    on_press:
      - display_menu.up: scanner_menu

  - platform: gpio
    pin:
      number: D4
      mode: INPUT_PULLUP
      inverted: True
    name: "Button Down"
    on_press:
      - display_menu.down: scanner_menu

  - platform: gpio
    pin:
      number: D5
      mode: INPUT_PULLUP
      inverted: True
    name: "Button Select"
    on_press:
      - display_menu.enter: scanner_menu
