# Features:
#  singleshort: x Sekunden an, dann aus (via Hardwareschalter als auch MQTT)
#  doubleshort: y Sekunden an, dann aus (via Hardwareschalter als auch MQTT)
#  singlelong: Toggle, also wenn Licht an dann aus oder wenn Licht aus dann an (via Hardwareschalter als auch MQTT)
#  on_for: Licht kann via MQTT für in payload spezifizierte Anzahl an Sekunden angeschaltet werden (paylad darf auch "singleshort", "doubleshort" oder "singlelong" sein)
#  x und y können via mqtt gesetzt werden (werden auf dem Gerät persistiert)
#  Licht wird morgens kurz nach Sonnenaufgang automatisch immer ausgeschaltet
#  Über alle Wege kann "nachgetastet" werden -> Konkret: Timer wird auf den neuen Wert gesetzt, z.B. singleclick: Timer startet wieder bei x, d.h. es wird NICHT aufsummiert (neue Zeit = Restzeit + x) sondern neue Zeit = x, das bedeutet entsprechend auch, dass, falls die Restzeit >x ist man damit die Restzeit auf x reduzieren kann, Beispiel: doublelick=5m, singlecklick=2m, doubleklick ausgelöst, Restzeit noch 4 Minuten, dann singleclick -> Restzeit dann 2m (und eben nicht 4m+2m=6m), it's not a bug it's feature. Damit kann z.B. auch ein dauerhaft angeschaltetes Licht mit dem Taster auf eine Rest-An-Zeit von 2m gsetzt werden. 
# on_for, d.h. Zeit bis zum ausschalten wird, falls countdown aktiv, sekündlich publiziert
# Alle Shelly Funktionen wie Spannung-/Strommessung, Brownout-/Überlast/Hitze-Detection
# Feature-Ideen
#  Sperrzeiten, z.B. zwischen Sonnenaufgang+15 bis Sonnenuntergang-15, aber dann mit Möglichkeit des overrulens, dies sollte aber entweder auch nur für x Minuten gelten oder täglich wieder zurückgenomm werden. Oder man sperrt z.B. alles ausser dem longpress, dann wäre longpress immer möglich. 
#  Alert wenn sensor/power/state nicht 0 und ausserhalb von 450W +/- 10% -> Birne defekt

substitutions:
  device_name: "shelly-ssr"
  # Higher value gives lower watt readout
  current_res: "0.001"
  # Lower value gives lower voltage readout
  voltage_div: "1925"

esphome:
  name: ${device_name}
  platformio_options:
    board_build.f_cpu: 160000000L

<<: !include common/substitutions.yaml
packages: 
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  management: !include common/management.yaml
  sun: !include common/sun.yaml

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

globals:
   - id: on_for_timer
     type: int
     restore_value: no
     initial_value: '0'
   - id: sleeptime
     type: int
     restore_value: no
     initial_value: '0'
   - id: singleshortdelay
     type: int
     restore_value: yes
     initial_value: '120'
   - id: doubleshortdelay
     type: int
     restore_value: yes
     initial_value: '300'

sun:
  on_sunrise:
    - elevation: 10°
      then:
        - switch.turn_off: relay_1

text_sensor:
  # Receive sleep time over MQTT
  - platform: mqtt_subscribe
    id: set_on_for
    topic: "${device_name}/on_for/set"
    on_value:
      - then:
        - lambda: |-
              if (x == "singlelong") {
                id(delay_script).stop();
                id(relay_1).toggle();
                return;
              }
              auto val = (x == "singleshort")
                ? id(singleshortdelay)
                : (x == "doubleshort")
                  ? id(doubleshortdelay)
                  : esphome::parse_number<int>(x.c_str()).value_or(-1);
              if (val >= 0) {
                id(sleeptime) = val;
                id(delay_script).execute();
              }

sensor:
  - platform: sun
    id: sun_elevation
    type: elevation
  - platform: template
    id: get_on_for
    name: on_for
    accuracy_decimals: 0
    update_interval: never # published explicitly in script during countdown
  - platform: mqtt_subscribe
    id: set_singleshortdelay
    topic: "${device_name}/singleshortdelay/set"
    on_value:
      - then:
        - globals.set:
            id: singleshortdelay
            value: !lambda return int(x);
  - platform: mqtt_subscribe
    id: set_doubleshortdelay
    topic: "${device_name}/doubleshortdelay/set"
    on_value:
      - then:
        - globals.set:
            id: doubleshortdelay
            value: !lambda return int(x);
  - platform: ntc
    sensor: temp_resistance_reading
    name: "Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - switch.turn_off: relay_1
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO32
    attenuation: 12db
  - platform: adc
    name: "Relay Supply Voltage"
    pin: GPIO33
    attenuation: 12db
    filters:
      - multiply: 8
  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO23
      inverted: true
    cf_pin: GPIO5
    cf1_pin: GPIO18
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "Current"
      unit_of_measurement: A
      accuracy_decimals: 3
      filters:
        # Map from sensor -> measured value
        - calibrate_linear:
          -  0.0000 ->  0.00
          -  0.2140 ->  0.22
          -  3.1600 ->  3.31
          -  6.4435 ->  6.72
          - 13.0388 -> 13.57
    voltage:
      name: "Voltage"
      unit_of_measurement: V
      accuracy_decimals: 1
    power:
      name: "Power"
      unit_of_measurement: W
      id: power
      filters:
        # Map from sensor -> measured value
        - calibrate_linear:
          -    0.0  ->    0.0
          -   49.27 ->   51.0
          -  727.76 ->  762.0
          - 1483.00 -> 1550.0
          - 3004.91 -> 3140.0
        # Make everything below 2W appear as just 0W.
        # Furthermore it corrects 0.5W for the power usage of the plug.
        - lambda: auto cor = (x - 0.5); if (cor < 2) return 0; else return cor;
      on_value_range:
        - above: "3600"
          then:
            - switch.turn_off: relay_1
    change_mode_every: 2
    update_interval: 10s
  - platform: total_daily_energy
    name: "Daily energy consumed"
    power_id: power
    filters:
        - multiply: 0.001
    unit_of_measurement: kWh

binary_sensor:
  - platform: gpio
    pin: GPIO4
    id: button_1

    on_multi_click:
    - timing:
        - ON for at most 1.5s
        - OFF for at least 0.25s
      then:
#       - logger.log: "Single Short Clicked"
        - globals.set:
            id: sleeptime
            value: !lambda return id(singleshortdelay);
        - script.execute: delay_script
    - timing:
        - ON for at most 1s
        - OFF for at most 0.25s
        - ON for at most 1s
        - OFF for at least 0.25s
      then:
#       - logger.log: "Double Short Clicked"
        - globals.set:
            id: sleeptime
            value: !lambda return id(doubleshortdelay);
        - script.execute: delay_script
    - timing:
        - ON for at least 1.5s
      then:
#       - logger.log: "Single Long Clicked"
        - script.stop: delay_script
        - switch.toggle: relay_1

switch:
# connected to hardware and not exposed
  - platform: gpio
    id: relay_1
    pin: GPIO26

# exposed as mqtt (so here we can stop the script on any message received)
  - platform: template
    name: "relay_1"
    lambda: return id(relay_1).state;
    turn_on_action:
      then:
        - script.stop: delay_script
        - switch.turn_on: relay_1
    turn_off_action:
      then:
        - script.stop: delay_script
        - switch.turn_off: relay_1

script:
  - id: delay_script
    mode: restart
    then:
    - switch.turn_on: relay_1
    - globals.set:
        id: on_for_timer
        value: !lambda return id(sleeptime);
    - while:
        condition:
          lambda: 'return id(on_for_timer) > 0;'
        then:
        - delay: 1s
        - globals.set:
            id: on_for_timer
            value: !lambda return id(on_for_timer) - 1;
        - sensor.template.publish:
            id: get_on_for
            state: !lambda return id(on_for_timer);
    - switch.turn_off: relay_1
  
